[project]
name = "csvwildcards"
description = "A ComfyUI custom node that provides dynamic text substitution using wildcards and CSV files. Perfect for creating varied prompts with consistent relationships between terms."
version = "1.0.0"
license = {file = "LICENSE"}

[project.urls]
Repository = "https://github.com/illuminatianon/comfyui-csvwildcards"
#  Used by Comfy Registry https://comfyregistry.org

[tool.comfy]
PublisherId = "illuminatianon"
DisplayName = "comfyui-csvwildcards"
Icon = ""
